# -*- coding: utf-8 -*-
"""GYM_Management_System_By _Square_Goals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwAjxUJL28-LFttehK-Twzk8z8DwQwE-
"""

# ================================
# ✅ IMPORTS
# ================================
import time  # ✅ Add this at the top

# ================================
# ✅ Auto-pause after each action
# ================================
def pause():
    time.sleep(0.1)  # Pauses for 0.1 seconds
from datetime import datetime
import matplotlib.pyplot as plt
import pandas as pd
import getpass
import os
from datetime import datetime
from abc import ABC, abstractmethod

# ================================
# ✅ Base Class
# ================================

class Person:
    """
    🔹 Base class representing a general person in the system.
    Used for Admin, Trainer, or Member roles.
    """
    def __init__(self, name, role):
        self.name = name        # Stores the person's full name
        self.role = role        # Stores the role (Admin/Trainer/Member)

    def get_details(self):
        """
        📝 Returns a formatted string with the person's name and role.
        """
        return f"👤 Name: {self.name}, Role: {self.role}"

    def view_status(self):
        """
        ✅ Shows the active status of the user.
        """
        print("✅ Status: Active")

# ================================
# 🤖 AI Chatbot
# ================================

def ai_chatbot():
    """
    🧠 Simple rule-based chatbot that assists users with gym-related queries.
    Responds to keywords in user input. Type 'exit' to quit the chatbot.
    """

    print("\n🤖 AI Chatbot Assistant (type 'exit' to quit)")

    # Infinite loop to keep the chatbot running until user types 'exit'
    while True:
        query = input("🗨️ You: ").strip().lower()  # Take user input, remove extra spaces, and convert to lowercase

        # ✅ Exit condition
        if query == "exit":
            print("🤖 Chatbot: Goodbye!")
            break

        # ✅ Responses based on keyword detection
        elif "open" in query and "time" in query:
            print("🤖 Chatbot: Gym opens at 6 AM and closes at 10 PM.")

        elif "trainer" in query and "book" in query:
            print("🤖 Chatbot: Go to 'Book Trainer' in member dashboard.")

        elif "classes" in query:
            print("🤖 Chatbot: Check 'View Class Schedule'.")

        elif "payment" in query:
            print("🤖 Chatbot: Use 'Make Payment' from your dashboard.")

        elif "attendance" in query:
            print("🤖 Chatbot: Mark it using 'Mark Attendance'.")

        elif "help" in query:
            print("🤖 Chatbot: You can ask about classes, trainers, schedule, or payment.")

        # ✅ Default fallback if input doesn't match known queries
        else:
            print("🤖 Chatbot: Sorry, I didn't understand. Try again.")

"""# **What Questions We can Ask from ChatBot**

**🕒 Gym Timing**

1.   What are your open and close times?

**🧑‍🏫 Trainer Booking**

1.   Where do I book my personal trainer?

**🗓️ Classes**

1.   What classes are available?

**💳 Payment**

1.   Where is the payment option?

**📅 Attendance**

1.   I forgot to mark my attendance

**🆘 Help**

1.   Show help
"""

from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt

class Admin(Person):
    def __init__(self, name):
        super().__init__(name, "Admin")

    # 1. Add Trainer
    def add_trainer(self):
        print("\n➕ Add Trainer")
        name = input("Enter trainer name: ")
        specialization = input("Enter specialization: ")
        phone = input("Enter phone number: ")
        salary = input("Enter salary: ")

        with open("trainers.txt", "a") as f:
            f.write(f"{name},{specialization},{phone},{salary}\n")
        print(f"✅ Trainer {name} added successfully!")


    # 2. Remove Trainer
    def remove_trainer(self):
        name = input("Enter Trainer Name to Remove: ")
        try:
            with open("trainers.txt", "r") as f:
                trainers = f.readlines()
            with open("trainers.txt", "w") as f:
                for t in trainers:
                    if t.strip() != name:
                        f.write(t)
            print(f"🗑️ Trainer '{name}' removed.")
        except FileNotFoundError:
            print("⚠️ Trainer file not found.")

    # 3. Add Member
    def add_member(self):
        print("\n➕ Add Member")
        name = input("Enter member name: ")
        age = input("Enter age: ")
        phone = input("Enter phone number: ")
        membership_type = input("Enter membership type (Basic/Premium/VIP): ")

        with open("members.txt", "a") as f:
            f.write(f"{name},{age},{phone},{membership_type}\n")
        print(f"✅ Member {name} added successfully!")

    # 4. Remove Member
    def remove_member(self):
        name = input("Enter Member Name to Remove: ")
        try:
            with open("members.txt", "r") as f:
                members = f.readlines()
            with open("members.txt", "w") as f:
                for m in members:
                    if m.strip() != name:
                        f.write(m)
            print(f"🗑️ Member '{name}' removed.")
        except FileNotFoundError:
            print("⚠️ Member file not found.")

    # 5. Create Schedule
    def create_schedule(self):
        schedule = input("Enter Class Schedule (Day - Time): ")
        with open("schedule.txt", "a") as f:
            f.write(schedule + "\n")
        print("🗕️ Schedule added successfully.")

    # 6. Mark Attendance
    def mark_attendance(self):
        person = input("Enter Name: ")
        with open("attendance.txt", "a") as f:
            f.write(f"{person},Admin,{datetime.now()}\n")
        print("🗜️ Attendance marked.")

    # 7. Maintenance
    def record_maintenance(self):
        record = input("Enter maintenance details: ")
        with open("maintenance.txt", "a") as f:
            f.write(f"{record} - {datetime.now()}\n")
        print("🔧 Maintenance recorded.")

    # 8. Check Salary
    def check_salary_status(self):
        try:
            with open("salary.txt", "r") as f:
                print("💵 Salary Records:\n" + f.read())
        except FileNotFoundError:
            print("⚠️ Salary file not found.")

    # 9. Generate Report
    def generate_report(self):
        with open("report.txt", "w") as f:
            f.write("📋 GYM SYSTEM REPORT\n")
            for file, label in [("members.txt", "Members"), ("trainers.txt", "Trainers")]:
                try:
                    count = len(open(file).readlines())
                except FileNotFoundError:
                    count = 0
                f.write(f"{label}: {count}\n")
        print("📄 Report generated.")

    # 10. Attendance Chart
    def view_attendance_plot(self):
        try:
            df = pd.read_csv("attendance.txt", header=None, names=["Name", "Role", "Date"])
            df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
            daily_counts = df["Date"].dt.date.value_counts().sort_index()
            daily_counts.plot(kind="bar", figsize=(10, 5), title="📊 Attendance Over Time", color="skyblue")
            plt.xlabel("Date")
            plt.ylabel("Entries")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.pause(0.1)
            plt.show()
        except Exception as e:
            print(f"❌ Error: {e}")

    # 11. Payment Chart
    def view_payment_plot(self):
        try:
            df = pd.read_csv("payments.txt", header=None, names=["Name", "Amount", "Date"])
            df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
            daily_total = df.groupby(df["Date"].dt.date)["Amount"].sum()
            daily_total.plot(kind="line", marker="o", figsize=(10, 5), title="💰 Payments Over Time", color="green")
            plt.xlabel("Date")
            plt.ylabel("Total Payment")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.pause(0.1)
            plt.show()
        except Exception as e:
            print(f"❌ Error: {e}")

    # 12. Assign Task
    def assign_task(self):
        trainer_name = input("👤 Enter Trainer Name: ")
        task = input("📝 Enter Task to Assign: ")
        date = input("📅 Enter Due Date (YYYY-MM-DD): ")
        with open("assignments.txt", "a") as f:
            f.write(f"{trainer_name},{task},{date}\n")
        print(f"✅ Task assigned to {trainer_name} for {date}.")

    # 13 & 14. Search Trainer/Member
        # 13 & 14. Search Trainer/Member
    # 13 & 14. Search Trainer/Member (Single Method)
    # 13 & 14. Search Trainer or Member
    def search_person(self, role):
        name = input(f"🔍 Enter {role} Name to Search: ").strip().lower()
        file = "trainers.txt" if role == "Trainer" else "members.txt"

        try:
            with open(file, "r") as f:
                found = False
                for line in f:
                    parts = line.strip().split(",")
                    if parts and parts[0].strip().lower() == name:
                        print(f"✅ {role} found: {line.strip()}")
                        found = True
                        break
                if not found:
                    print(f"❌ {role} '{name}' not found.")
        except FileNotFoundError:
            print(f"⚠️ {file} not found.")

    # 15. Dashboard Summary
    def dashboard_summary(self):
        print("\n📊 Admin Dashboard Summary:")
        files = {
            "Trainers": "trainers.txt",
            "Members": "members.txt",
            "Schedules": "schedule.txt",
            "Attendance": "attendance.txt"
        }
        for label, file in files.items():
            try:
                with open(file, "r") as f:
                    print(f"{label}: {len(f.readlines())}")
            except FileNotFoundError:
                print(f"{label}: 0")

    # 16. View Feedbacks
    def view_feedbacks(self):
        try:
            with open("feedback.txt", "r") as f:
                print("🗨️ Member Feedbacks:\n" + f.read())
        except FileNotFoundError:
            print("⚠️ No feedbacks found.")

    # 17. Trainer Performance Report
    def trainer_performance_report(self):
        try:
            with open("assignments.txt", "r") as f:
                tasks = f.readlines()
                count = {}
                for t in tasks:
                    trainer = t.strip().split(",")[0]
                    count[trainer] = count.get(trainer, 0) + 1
                print("📈 Trainer Performance:")
                for trainer, task_count in count.items():
                    print(f"{trainer}: {task_count} task(s)")
        except FileNotFoundError:
            print("⚠️ No task data.")

    # 18. Add Membership Package
    def add_membership_package(self):
        name = input("📦 Package Name: ")
        price = input("💰 Price: ")
        duration = input("📆 Duration (months): ")
        with open("packages.txt", "a") as f:
            f.write(f"{name},{price},{duration}\n")
        print(f"✅ Package '{name}' added.")

    # 19. Assign Package to Member
    def assign_membership_package_to_member(self):
        member = input("👤 Member Name: ")
        package = input("📦 Package Name: ")
        with open("assigned_packages.txt", "a") as f:
            f.write(f"{member},{package},{datetime.now().date()}\n")
        print(f"✅ Assigned '{package}' to {member}.")

    # 20. Track Expiry
    def track_membership_expiry(self):
        try:
            with open("assigned_packages.txt", "r") as f:
                print("⏳ Membership Expiry Status:")
                for line in f:
                    member, pkg, start_date = line.strip().split(",")
                    start = datetime.strptime(start_date, "%Y-%m-%d")
                    expiry = start + timedelta(days=30)
                    print(f"{member} ({pkg}) expires on {expiry.date()}")
        except FileNotFoundError:
            print("⚠️ No assigned packages found.")

    # 21. Add Class
    def add_class(self):
        class_name = input("🏋️ Class Name: ")
        time = input("🕓 Time: ")
        trainer = input("👤 Trainer: ")
        with open("classes.txt", "a") as f:
            f.write(f"{class_name},{time},{trainer}\n")
        print(f"✅ Class '{class_name}' added.")

    # 22. Enroll Member in Class
    def enroll_member_in_class(self):
        member = input("👤 Member Name: ")
        class_name = input("🏋️ Class Name: ")
        with open("enrollments.txt", "a") as f:
            f.write(f"{member},{class_name}\n")
        print(f"✅ {member} enrolled in '{class_name}'.")

    # 23. Manage Equipment
    def manage_equipment_inventory(self):
        name = input("🏋️ Equipment Name: ")
        qty = input("🔢 Quantity: ")
        with open("equipment.txt", "a") as f:
            f.write(f"{name},{qty}\n")
        print(f"✅ Equipment '{name}' added.")

    # 24. Set Equipment Status
    def set_equipment_status(self):
        name = input("🏋️ Equipment Name: ")
        status = input("⚙️ Status (Working/Repair): ")
        with open("equipment_status.txt", "a") as f:
            f.write(f"{name},{status}\n")
        print(f"✅ Status set for '{name}' as '{status}'.")

# ================================
# ✅ Trainer Class
# ================================
class Trainer(Person):
    def __init__(self, name):
        super().__init__(name, "Trainer")

    # ------------------------------
    # ✅ Programs
    # ------------------------------
    def add_program(self):
        prog = input("Program Name: ")
        with open("programs.txt", "a") as f:
            f.write(prog + "\n")
        print("📘 Program added.")

    # ------------------------------
    # ✅ View Assigned Tasks
    # ------------------------------
    def view_assigned(self):
        try:
            with open("assignments.txt", "r") as f:
                found = False
                for line in f:
                    if line.startswith(f"{self.name}:"):
                        print(line.strip())
                        found = True
                if not found:
                    print("❌ No tasks assigned.")
        except FileNotFoundError:
            print("⚠️ Assignments file not found.")

    # ------------------------------
    # ✅ Mark Attendance
    # ------------------------------
    def mark_attendance(self):
        with open("attendance.txt", "a") as f:
            f.write(f"{self.name},Trainer,{datetime.now()}\n")
        print("🗜️ Attendance marked.")

    # ------------------------------
    # ✅ View Equipment
    # ------------------------------
    def view_equipment(self):
        try:
            with open("equipment.txt", "r") as f:
                print("\n🔧 Equipment List:")
                print(f.read())
        except FileNotFoundError:
            print("⚠️ Equipment file not found.")

    # ------------------------------
    # ✅ NEW FEATURE: View Member Profiles
    # ------------------------------
    def view_member_profiles(self):
        try:
            with open("members.txt", "r") as f:
                print("\n👥 Member Profiles:")
                for line in f:
                    print(f"- {line.strip()}")
        except FileNotFoundError:
            print("⚠️ Members file not found.")

    # ------------------------------
    # ✅ NEW FEATURE: Update Member Progress
    # ------------------------------
    def update_member_progress(self):
        member = input("Enter Member Name: ")
        note = input("Enter Progress Note: ")
        with open("progress_notes.txt", "a") as f:
            f.write(f"{member}: {note}\n")
        print("✅ Progress note saved.")

    # ------------------------------
    # ✅ NEW FEATURE: Manage Personal Training Sessions
    # ------------------------------
    def manage_personal_training_sessions(self):
        action = input("1) View Sessions  2) Add Session  Choose: ")
        if action == "1":
            try:
                with open("personal_sessions.txt", "r") as f:
                    print("\n📅 Personal Training Sessions:")
                    for line in f:
                        if line.startswith(self.name + ":"):
                            print(line.strip())
            except FileNotFoundError:
                print("⚠️ No personal sessions found.")
        elif action == "2":
            member = input("Enter Member Name: ")
            time = input("Enter Session Time: ")
            with open("personal_sessions.txt", "a") as f:
                f.write(f"{self.name}: {member} at {time}\n")
            print("✅ Personal training session added.")
        else:
            print("❌ Invalid option.")

    # ------------------------------
    # ✅ NEW FEATURE: View My Schedule
    # ------------------------------
    def view_my_schedule(self):
        try:
            with open("schedule.txt", "r") as f:
                print("\n📅 Class Schedule:")
                print(f.read())
        except FileNotFoundError:
            print("⚠️ Schedule file not found.")

    # ------------------------------
    # ✅ NEW FEATURE: Request Equipment Maintenance
    # ------------------------------
    def request_equipment_maintenance(self):
        eq = input("Enter Equipment Name: ")
        issue = input("Describe Issue: ")
        with open("maintenance_requests.txt", "a") as f:
            f.write(f"{self.name}: {eq} - {issue}\n")
        print("✅ Maintenance request submitted.")

# ================================
# ✅ Member Class
# ================================
class Member(Person):
    def __init__(self, name):
        super().__init__(name, "Member")

    # ------------------------------
    # ✅ View Status
    # ------------------------------
    def view_status(self):
        print("✅ Status: Active")

    # ------------------------------
    # ✅ Make Payment
    # ------------------------------
    def make_payment(self):
        amt = input("Enter amount: ")
        with open("payments.txt", "a") as f:
            f.write(f"{self.name},{amt},{datetime.now()}\n")
        print("💰 Payment recorded.")

    # ------------------------------
    # ✅ Book Trainer
    # ------------------------------
    def book_trainer(self):
        trainer = input("Trainer name: ")
        with open("bookings.txt", "a") as f:
            f.write(f"{self.name} booked {trainer} at {datetime.now()}\n")
        print("🗕️ Trainer booked.")

    # ------------------------------
    # ✅ View Equipment
    # ------------------------------
    def view_equipment(self):
        try:
            with open("equipment.txt", "r") as f:
                print("\n🔧 Equipment List:")
                print(f.read())
        except FileNotFoundError:
            print("⚠️ Equipment file not found.")

    # ------------------------------
    # ✅ View Schedule
    # ------------------------------
    def view_schedule(self):
        try:
            with open("schedule.txt", "r") as f:
                print("\n🗕️ Class Schedule:")
                print(f.read())
        except FileNotFoundError:
            print("⚠️ Schedule file not found.")

    # ------------------------------
    # ✅ Mark Attendance
    # ------------------------------
    def mark_attendance(self):
        with open("attendance.txt", "a") as f:
            f.write(f"{self.name},Member,{datetime.now()}\n")
        print("🗜️ Attendance marked.")

    # ------------------------------
    # ✅ Give Feedback
    # ------------------------------
    def give_feedback(self):
        fb = input("Feedback: ")
        with open("feedback.txt", "a") as f:
            f.write(f"{self.name}: {fb}\n")
        print("✅ Feedback saved.")

    # ------------------------------
    # ✅ Edit Profile
    # ------------------------------
    def edit_profile(self):
        new_name = input("Enter new name: ")
        lines = open("users.txt", "r").readlines()
        with open("users.txt", "w") as f:
            for line in lines:
                uname, pwd, role = line.strip().split(",")
                if uname == self.name and role == "Member":
                    f.write(f"{new_name},{pwd},{role}\n")
                    self.name = new_name
                else:
                    f.write(line)
        print("✅ Profile updated.")

    # ------------------------------
    # ✅ NEW FEATURE: View Class Schedule
    # ------------------------------
    def view_class_schedule(self):
        try:
            with open("classes.txt", "r") as f:
                print("\n📅 Class Schedule:")
                print(f.read())
        except FileNotFoundError:
            print("⚠️ No class schedule found.")

    # ------------------------------
    # ✅ NEW FEATURE: Book Class
    # ------------------------------
    def book_class(self):
        class_name = input("Enter Class Name: ")
        with open("class_bookings.txt", "a") as f:
            f.write(f"{self.name} booked {class_name} at {datetime.now()}\n")
        print("✅ Class booked.")

    # ------------------------------
    # ✅ NEW FEATURE: View Trainer Profiles
    # ------------------------------
    def view_trainer_profiles(self):
        try:
            with open("trainers.txt", "r") as f:
                print("\n🏋️ Trainer Profiles:")
                for line in f:
                    print(f"- {line.strip()}")
        except FileNotFoundError:
            print("⚠️ No trainer profiles found.")

    # ------------------------------
    # ✅ NEW FEATURE: View My Progress
    # ------------------------------
    def view_my_progress(self):
        try:
            with open("progress_notes.txt", "r") as f:
                print("\n📈 Your Progress Notes:")
                found = False
                for line in f:
                    if line.lower().startswith(self.name.lower() + ":"):
                        print(line.strip())
                        found = True
                if not found:
                    print("⚠️ No progress notes found for you.")
        except FileNotFoundError:
            print("⚠️ No progress notes found.")

    # ------------------------------
    # ✅ NEW FEATURE: View Announcements
    # ------------------------------
    def view_announcements(self):
        try:
            with open("announcements.txt", "r") as f:
                print("\n📢 Announcements:")
                print(f.read())
        except FileNotFoundError:
            print("⚠️ No announcements found.")

# ================================
# ✅ Equipment Class
# ================================

class Equipment:
    """
    ⚙️ Handles equipment-related actions for the gym.
    Currently supports adding equipment to the inventory file.
    """

    @staticmethod
    def add_equipment():
        """
        ➕ Prompts user to enter the name of new equipment and saves it to 'equipment.txt'.
        This method is static because it does not depend on any instance variables.
        """
        eq = input("Enter equipment name: ")  # Ask for equipment name
        with open("equipment.txt", "a") as f:
            f.write(eq + "\n")  # Append equipment name to the file
        print("🔧 Equipment added.")  # Confirmation message

# ================================
# ✅ User Authentication Functions
# ================================
def register_user():
    print("\n📝 Register New User")
    uname = input("Username: ")
    pwd = getpass.getpass("Password: ")
    role = input("Role (Admin/Trainer/Member): ").capitalize()

    if role not in ["Admin", "Trainer", "Member"]:
        print("❌ Invalid role. Must be Admin, Trainer, or Member.")
        return

    # Check if username already exists
    if os.path.exists("users.txt"):
        with open("users.txt", "r") as f:
            for line in f:
                if uname == line.strip().split(",")[0]:
                    print("⚠️ Username already exists. Choose another.")
                    return

    # Register new user
    with open("users.txt", "a") as f:
        f.write(f"{uname},{pwd},{role}\n")
    print("✅ User registered successfully!")

def login_user():
    uname = input("Username: ")
    pwd = getpass.getpass("Password: ")

    if not os.path.exists("users.txt"):
        print("❌ No registered users found. Please register first.")
        return None, None

    with open("users.txt", "r") as f:
        for line in f:
            u, p, r = line.strip().split(",")
            if uname == u and pwd == p:
                print(f"✅ Logged in successfully as {r}!")
                return u, r

    print("❌ Invalid credentials. Please try again.")
    return None, None

# ================================
# ✅ Main Program Loop
# ================================
def run_system():
    while True:
        # 🎯 Display the main menu
        print("\n🏋️ Welcome to Square Goals Gym System 🏋️")
        print("1. Login 🔐")
        print("2. Register 📝")
        print("3. ChatBot 🤖")
        print("4. Exit ❌")

        # 🧾 Get user choice
        ch = input("Choose an option: ")

        # ======================
        # 🔐 Login
        # ======================
        if ch == "1":
            uname, role = login_user()  # login_user() returns username and role
            if not uname:
                continue  # if login fails, return to main menu

            # -------------------------
            # ✅ Admin Dashboard Logic
            # -------------------------
            if role == "Admin":
                a = Admin(uname)  # create Admin object
                while True:
                    # Display all 24 Admin options
                    print("\n-----------Admin Dashboard-----------")
                    print(
                        "1:Add Trainer  2:Remove Trainer  3:Add Member  4:Remove Member\n"
                        "5:Schedule  6:Attendance  7:Maintenance  8:Salary\n"
                        "9:Report  10:Attendance Chart  11:Payment Chart  12:Assign Task\n"
                        "13:Search Trainer  14:Search Member  15:Dashboard\n"
                        "16:View Feedbacks  17:Trainer Performance Report\n"
                        "18:Add Membership Package  19:Assign Package\n"
                        "20:Track Membership Expiry  21:Add Class  22:Enroll Member in Class\n"
                        "23:Manage Equipment Inventory  24:Set Equipment Status  25:View Member Status   26:Logout"
                    )
                    opt = input("Choose an option: ")

                    if opt == "26":
                        break  # logout from admin dashboard

                    # 📍 Admin actions map
                    {
                        "1":  a.add_trainer,
                        "2": a.remove_trainer,
                        "3":  a.add_member,
                        "4": a.remove_member,
                        "5": a.create_schedule,
                        "6": a.mark_attendance,
                        "7": a.record_maintenance,
                        "8": a.check_salary_status,
                        "9": a.generate_report,
                        "10": a.view_attendance_plot,
                        "11": a.view_payment_plot,
                        "12": a.assign_task,
                        "13": lambda: a.search_person("Trainer"),
                        "14": lambda: a.search_person("Member"),
                        "15": a.dashboard_summary,
                        "16": a.view_feedbacks,
                        "17": a.trainer_performance_report,
                        "18": a.add_membership_package,
                        "19": a.assign_membership_package_to_member,
                        "20": a.track_membership_expiry,
                        "21": a.add_class,
                        "22": a.enroll_member_in_class,
                        "23": a.manage_equipment_inventory,
                        "24": a.set_equipment_status,
                        "25": a.view_status

                    }.get(opt, lambda: print("❌ Invalid option."))()

            # -------------------------
            # ✅ Trainer Dashboard Logic
            # -------------------------
            elif role == "Trainer":
                t = Trainer(uname)  # create Trainer object
                while True:
                    # Show all Trainer options
                    print("\n----------Trainer Dashboard----------")
                    print(
                        "1:Add Program  2:View Assigned  3:Attendance  4:Equipment\n"
                        "5:View Member Profiles  6:Update Member Progress\n"
                        "7:Manage Personal Training Sessions  8:View My Schedule\n"
                        "9:Request Equipment Maintenance  10:View Member Status  11:Logout"
                    )
                    opt = input("Choose an option: ")

                    if opt == "11":
                        break  # logout from trainer dashboard

                    # 📍 Trainer actions map
                    {
                        "1": t.add_program,
                        "2": t.view_assigned,
                        "3": t.mark_attendance,
                        "4": t.view_equipment,
                        "5": t.view_member_profiles,
                        "6": t.update_member_progress,
                        "7": t.manage_personal_training_sessions,
                        "8": t.view_my_schedule,
                        "9": t.request_equipment_maintenance,
                        "10": t.view_status


                    }.get(opt, lambda: print("❌ Invalid option."))()

            # -------------------------
            # ✅ Member Dashboard Logic
            # -------------------------
            elif role == "Member":
                m = Member(uname)  # create Member object
                while True:
                    # Show all Member options
                    print("\n------------Member Dashboard------------")
                    print(
                        "1:Status  2:Payment  3:Book Trainer  4:Equipment\n"
                        "5:Schedule  6:Attendance  7:Feedback  8:Edit Profile\n"
                        "9:View Class Schedule  10:Book Class  11:View Trainer Profiles\n"
                        "12:View My Progress  13:View Announcements  14:Logout"
                    )
                    opt = input("Choose an option: ")

                    if opt == "14":
                        break  # logout from member dashboard

                    # 📍 Member actions map
                    {
                        "1": m.view_status,
                        "2": m.make_payment,
                        "3": m.book_trainer,
                        "4": m.view_equipment,
                        "5": m.view_schedule,
                        "6": m.mark_attendance,
                        "7": m.give_feedback,
                        "8": m.edit_profile,
                        "9": m.view_class_schedule,
                        "10": m.book_class,
                        "11": m.view_trainer_profiles,
                        "12": m.view_my_progress,
                        "13": m.view_announcements
                    }.get(opt, lambda: print("❌ Invalid option."))()

        # ======================
        # 📝 Registration
        # ======================
        elif ch == "2":
            register_user()

        # ======================
        # 🤖 Chatbot
        # ======================
        elif ch == "3":
            ai_chatbot()

        # ======================
        # ❌ Exit the system
        # ======================
        elif ch == "4":
            print("Exiting... Goodbye")
            break

        # ======================
        # ❌ Invalid input
        # ======================
        else:
            print("❌ Invalid choice. Please try again.")

# ================================
# ✅ Run the System
# ================================
if __name__ == "__main__":
    run_system()